### PR TITLE
Readme: Fix link to Yadda docs

### PR DESCRIPTION
**Pull request by lolmaus**

### CODE REVIEW

**Comment by albertjan** [comment]
Thanks @lolmaus, I don't really know if people still use this but this won't hurt. 😄

**Comment by lolmaus** [comment]
Oh yeah, that's my favorite thing.

I've been hired without a technical interview thanks to my experience in it.

And I'm building a follow-up addon, gonna share a link soon.

**Comment by albertjan** [comment]
I’ve sent you an invite for contributor. As you are much more likely to use it then me. 😊

**Comment by lolmaus** [comment]
@albertjan Thx, accepted!

As I understood, you're no longer using `ember-cli-yadda` yourself. Why? Are you no longer writing acceptance tests? Or have you switched to a different testing library? Or a different frontend framework?

Even though you're no longer using `ember-cli-yadda`, I still need your opinion on Yadda and `ember-cli-yadda`.

***

For us at https://kaliber5.de , Yadda and `ember-cli-yadda` have *a lot* of value. We use them in every project, and can't imaging writing tests without them.

That said, I've found traditional Yadda approach to be problematic and have come up with a number of know-hows and tricks to make using Yadda easier and more enjoyable.

Thanks to support from my employer kaliber5, I've built my approach into a follow-up addon.

Today I've published docs for it, please have a look: https://kaliber5.github.io/ember-cli-yadda-opinionated/versions/addon-docs/

The docs are still WIP, but should give you a good idea of the direction I'm taking Yadda to.

Now that you've made me a maintainer of `ember-cli-yadda`, I have a big temptation to move my approaches into `ember-cli-yadda` and make them the default.

The problem is that, though I strongly believe my approaches are very efficient, they are at the same time extremely opinionated and won't suit every app, especially existing ones.

So it makes total sense to have my approaches in a follow-up addon. Unfortunately, to use the follow-up addon, a developer must undo some of the work `ember-cli-yadda` is doing, which is also not optimal.

I have some ideas how to merge the two addons and keep the flexibility, but they require validation.

***

So please read through the docs of my addon and tell me what you think. Where should we draw the line, or should we merge the efforts into a single addon?

**Comment by lolmaus** [comment]
CC @simonihmig

**Comment by lolmaus** [comment]
@albertjan What do you think? ☝️

**Comment by albertjan** [comment]
I've been studying the docs, they look very good! I like the more modern approach. But I have to think a bit more about the ramifications 😄. With that I mean we could/should do away with some of the more esoteric things in ember-cli-yadda and adopt the opinionated way. But I do think we should keep the escape hatch to be able to do plain yadda tests.

**Comment by albertjan** [comment]
All in all I'm v-much in favour of merging the projects. I would also not mind transferring the repo to @kaliber5.

**Comment by simonihmig** [comment]
Hi @albertjan :) Chiming in here... 

> All in all I'm v-much in favour of merging the projects. 

I would object here! 😆 At least if that means literally making one addon out of the two. I think having a nicely layered approach, where `ember-cli-yadda` provides the foundation, which people can use by itself, and having the opinionated one on top makes sense in general. Where there is friction between the two, there are hopefully ways to reduce/eliminate that without giving up the layered approach. I guess we can discuss this, here or in direct conversations mit @lolmaus ...

> I would also not mind transferring the repo to @kaliber5.

I am open to that. Given my experience maintaining a bunch of addons, I tend to be a bit afraid of taking over the responsibility burden nowadays. :wink: But given that we are pretty much invested into the addon anyways, and thus have to take the maintenance burden anyways, if we want it or not, and both of us (me and Andrey) already have collaborator status and you seem to not use in anymore (that much), I guess this move would make sense!

So if you agree and this move is also preferable to you, feel free to do that! I guess you have to initiate this as the repo's owner?

**Comment by albertjan** [comment]
> I would object here! 😆

It makes sense to have the opinionated things in a separate plugin. But the api for the non opinionated version feels old and the step inheritance problems @lolmaus describes in the docs would also help the non-opinionated version. It would make adding the opinionated version later also easier because those things look much more alike.

**Pull request merged**
