### PR TITLE
Use ES6 in node

### PR DESCRIPTION
**Pull request by simonihmig**
Includes #60, so this needs to be merged first!

### CODE REVIEW

**Comment by albertjan** [comment]
Looks good! Love the class for the FeatureParser. Why is the `ember try:one` thing all of a sudden failing when it worked fine in #60?

**Comment by simonihmig** [comment]
This still contains an older commit of the Ember CLI 3.0 update. I just need to rebase this once #60 is merged, then it should be all green as well!

**Comment by simonihmig** [comment]
Rebased and green! :)

**Comment by sfbwalder** [comment]
I finally had a chance to test.  Sorry for my delay.  #60 and #61 worked fine for us.  Thanks for your work on this!

**Pull request merged**
